name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: gem install bundler jekyll
      - run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    needs: build
    uses: actions/deploy-pages@v2
